services:
  proxy:
    image: nginxproxy/nginx-proxy:1.8
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "8080:80"
  wordpress:
    # image: docker.io/bitpoke/wordpress-runtime:bedrock-php-8.3.14
    # image: ghcr.io/haipham22/fullstack-wordpress-develop
    build: .
    environment:
      - VIRTUAL_HOST=wp.dev.com
      - VIRTUAL_PORT=8080
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      # - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./vendor:/app/vendor
      - ./:/app
    # ports:
    #   - "8080:8080"
    restart: always
    # env_file:
    #   - .env
