services:
  wordpress:
    # image: docker.io/bitpoke/wordpress-runtime:bedrock-php-8.3.14
    image: ghcr.io/haipham22/fullstack-wordpress-develop
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "9001:8080"
    restart: always
    env_file:
      - .env