x-wordpress_tpl: &wordpress_tpl
  volumes:
    - .:/app
    - ./docker/custom.ini:/usr/local/etc/php/conf.d/custom.ini

services:
  wordpress:
    <<: *wordpress_tpl
    build: .
    ports:
      - "8443:8080"
  init_wordpress:
    <<: *wordpress_tpl
    image: wordpress:cli
    command: >
      /bin/sh -c '
      sleep 10;
      wp core download
      '
    depends_on:
      - wordpress
