x-wordpress_tpl: &wordpress_tpl
  env_file:
    - .env
  volumes:
    - .:/app
    - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini

services:
  wordpress:
    <<: *wordpress_tpl
    container_name: nginx-php-fpm-wordpress
    build: .
    ports:
      - "8443:8080"
  init_wordpress:
    <<: *wordpress_tpl
    build: .
    entrypoint: [
      "/bin/sh",
      "-c",
      "sleep 10; /entrypoint.sh"
    ]
    depends_on:
      - wordpress
