name: Auto Update WordPress Core, Plugins and Themes (Weekly)

on:
  schedule:
    - cron: '0 3 * * 1' # every Monday at 03:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Update dependencies
        run: |
          composer config repositories.wpackagist composer https://wpackagist.org
          composer update

      - name: Check for changes
        id: git-check
        run: |
          if [ -z "$(git status --porcelain composer.json composer.lock)" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create branch, commit and push
        if: steps.git-check.outputs.changed == 'true'
        id: git-commit
        run: |
          DATE=$(date +'%Y%m%d')
          BRANCH="auto/update-$DATE"
          git checkout -b "$BRANCH"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add composer.json composer.lock
          git commit -m "🔄 Weekly WordPress dependency update ($DATE)"
          git push origin "$BRANCH"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.git-commit.outputs.branch }}
          base: main
          title: "🔄 Weekly WordPress dependency update"
          body: |
            This pull request was automatically generated by the weekly WordPress dependency update workflow.
            - Updated WordPress core, plugins and themes via `composer update`.
          labels: |
            dependencies
            wordpress